web:
  restart: always
  build: ./web
  expose:
    - "8000"
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  restart: always
  build: ./nginx/
  volumes:
    - /vagrant:web:/static:ro
  ports:
    - "8000:80"
  links:
    - web:web
